### PR TITLE
Add command line arguments

### PR DESCRIPTION
**Pull request by CyberAndrii**
Hey! I'm using the console app from an automation tool and need more flexibility.

Arguments I've added:

```
  -o, --output    Directory to export to. Will be cleared if already exists.

  --logFile       (Default: AssetRipperConsole.log) File to log to.

  -q, --quit      (Default: false) Close console after export.

  --help          Display this help screen.

  --version       Display version information.

  value pos. 0    Required. Input files or directory to export.
```

### CODE REVIEW

**Comment by CyberAndrii** [comment]
It already works the same as before.

**Comment by ds5678** [comment]
My bad, I didn't try it. In that case, everything looks good.

**Comment by CyberAndrii** [comment]
recheck

**Comment by CyberAndrii** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ds5678** [comment]
Thank you!

**Pull request merged**
